#!/bin/sh 

echo "ifup ${PWD}"

. ./tap.conf

# 
# script to bring up the tun device in QEMU in bridged mode 
# first parameter is name of tap device (e.g. tap0)
#
# some constants specific to the local host - change to suit your host
#

/sbin/sysctl -w net.ipv4.ip_forward=1
#
# First take eth0 down, then bring it up with IP address 0.0.0.0 
#
#/sbin/ifconfig $ETH0DEV down
#/sbin/ifconfig $ETH0DEV promisc up
#/sbin/ifconfig $ETH0DEV 0.0.0.0 promisc up
#
# Bring up the tap device (name specified as first argument, by QEMU)
#
#/usr/sbin/openvpn --mktun --dev $1 --user `id -un`
#/sbin/tunctl -u `id -un` -t $1
/sbin/ifconfig $1 0.0.0.0 promisc up
#
# create the bridge between eth0 and the tap device
#
/usr/sbin/brctl addbr br0
# $1 is proveded by QEMU and is equal to $TAP_DEV
/usr/sbin/brctl addif ${LOCALNET_DEV} $1

# 
# only a single bridge so loops are not possible, turn off spanning tree protocol
#
#/usr/sbin/brctl stp br0 off 
# 
# Bring up the bridge with ETH0IPADDR and add the default route 
#
/sbin/ifconfig br0 $ETH0IPADDR netmask ${NETMASK} broadcast ${BROADCAST}
#/sbin/route add default gw ${GATEWAY}

/sbin/iptables -t nat -A POSTROUTING -o ${WORLDNET_DEV} -j MASQUERADE
/sbin/iptables -A FORWARD -i ${WORLDNET_DEV} -o ${LOCALNET_DEV} -m state --state RELATED,ESTABLISHED -j ACCEPT
/sbin/iptables -A FORWARD -i ${LOCALNET_DEV} -o ${WORLDNET_DEV} -j ACCEPT

#dnsmasq --interface=br0 --bind-interfaces --dhcp-range=192.168.0.15,192.168.255.254
#
# stop firewall - comment this out if you don't use Firestarter
#
#/sbin/service firestarter stop 
