#!/bin/sh 

# 
# Script to bring down and delete bridge br0 when QEMU exits 
# 
# Bring down eth0 and br0 
#

/sbin/ifconfig br0 down
/usr/sbin/brctl delbr br0 
/sbin/sysctl -w net.ipv4.ip_forward=0

